This code analyzes the self-disclosure measurement
It takes in the output of the object analysis software
```{r}
library('tidyverse')
library("readxl")
library('stringi')
library('ggpubr')
```
Load in data
```{r}
data <- read_excel("D:\\VU\\Validators\\Data\\object_analyse_output_man.xlsx")
```

```{r}
# Format data
df_topic <- data.frame(data$Disclosure...10, 
                       data$Disclosure...11,
                       data$Disclosure...12, 
                       data$Disclosure...13, 
                       data$Disclosure...14)
# combine columns
df_topic$new <- apply(df_topic, 1, function(row) paste(row, collapse = " "))
df_topic$newer <- apply(data.frame(df_topic$new), 1, function(row) (gsub("\\bNA\\b", "", row)))
# Count amount of topics
df_topic$t_count <- apply(data.frame(df_topic$newer), 1, function(row) (length(stri_remove_empty(strsplit(row,split = ' ')[[1]],na_empty=FALSE))))

# Count amount of respondents with no topics
length(which(df_topic$t_count == 0))
# Count amount of respondents
length(df_topic$t_count)
# Calculate percentage of topicless respondents
length(which(df_topic$t_count == 0))/length(df_topic$t_count)*100



```
Format data to [group, topic count] columns

```{r}
df_data = data.frame(group = data$`Additional columns...1`,
                     tcount = as.numeric(df_topic$t_count))
df_data = df_data[c(-1,-2),]
# Show summary of topic data
group_by(df_data,group) %>%
  summarise(count = n(), 
            mean = mean(tcount, na.rm=TRUE), 
            sd = sd(tcount, na.rm=TRUE))
```
Check for normal distribution
```{r}
shapiro.test(df_data$tcount[which(df_data$group=='A')])
shapiro.test(df_data$tcount[which(df_data$group=='B')])
shapiro.test(df_data$tcount[which(df_data$group=='C')])

```

Make boxplots of topic counts
Source: http://www.sthda.com/english/wiki/one-way-anova-test-in-r
```{r}

# set parameters for plots
par(mfrow=c(2,2))
datasets = c('df_data')

# Make a boxplot for each condition
for (dataset in datasets){
  cur_data = get(dataset)
  
  # Make boxplots
  y1 = ggboxplot(cur_data, x = "group", y = "tcount", 
           color = "group", palette = c("#00AFBB", "#E7B800", "#FC4E07"),
            order = c("A", "B", "C"),
            ylab = "Count", xlab = "Condition",
            ylim=c(0,6),
            main=dataset)
  # Make scattered boxplot
  y2 = ggline(cur_data, x = "group", y = "tcount", 
       add = c("mean_se", "jitter"), 
       order = c("A", "B", "C"),
       ylab = "Count", xlab = "Condition",
       main=dataset)
  
  show(y1)
  show(y2)
  
  }
```
Perform non-parametric anova
```{r}
kruskal.test(tcount ~ group, data = df_data)
```

Perform wilcoxon test
```{r}
# Check if p-value is significant
check_sig <- function(x,sidak){
  p = x$p.value
  # add * if p-value is below p-threshold
  if (p <= sidak){
      p = paste(toString(format(p, scientific = TRUE)), '*',sep="")
  }
  p = prettyNum(p, digits = 3)
  return (p)
}

# isolate data per condition
data_A = df_data$tcount[df_data$group=='A']
data_B = df_data$tcount[df_data$group=='B']
data_C = df_data$tcount[df_data$group=='C']

# calculate and print significance
sidak =  1-(1-0.05)^(1/(3))
print(check_sig(wilcox.test(data_A,data_B, paired = FALSE,na.rm=TRUE), sidak))
print(check_sig(wilcox.test(data_B,data_C, paired = FALSE,na.rm=TRUE), sidak))
print(check_sig(wilcox.test(data_A,data_C, paired = FALSE,na.rm=TRUE), sidak))

```
Write output in numbers to CSV for overview
```{r}
# Format data into one dataframe
max_length = max(length(data_A),
                 length(data_B),
                 length(data_C))
      
length(data_A) <- max_length
length(data_B) <- max_length
length(data_C) <- max_length

object_analysis_df <- data.frame(data_A, data_B, data_C)

write.csv(object_analysis_df, "object_analyse_numerical_output.csv", row.names=FALSE)



```


